name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        problem: [LSMOP1, LSMOP2, LSMOP3, LSMOP4, LSMOP5, LSMOP6, LSMOP7, LSMOP8, LSMOP9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Test 2
        run: matlab -batch "Population = LSMOP('init', '${{ matrix.problem }}', 2, 10); LSMOP('fitness', '${{ matrix.problem }}', 2, Population);"

      - name: Test 3
        run: matlab -batch "Population = LSMOP('init', '${{ matrix.problem }}', 3, 10); LSMOP('fitness', '${{ matrix.problem }}', 3, Population);"

      - name: Test 4
        run: matlab -batch "Population = LSMOP('init', '${{ matrix.problem }}', 4, 10); LSMOP('fitness', '${{ matrix.problem }}', 4, Population);"

      - name: PS
        run: matlab -batch "PF = LSMOP('PF', '${{ matrix.problem }}', 2, 100); writematrix(PF,'${{ matrix.problem }}.2D.pf','Delimiter',' ','FileType','text');"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.problem }}
          path: '*.pf'
