name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Test 2
        run: matlab -batch "Population = LSMOP('init', 'LSMOP9', 2, 10); LSMOP('fitness', 'LSMOP9', 2, Population);"

      - name: Test 3
        run: matlab -batch "Population = LSMOP('init', 'LSMOP9', 3, 10); LSMOP('fitness', 'LSMOP9', 3, Population);"

      - name: Test 4
        run: matlab -batch "Population = LSMOP('init', 'LSMOP9', 4, 10); LSMOP('fitness', 'LSMOP9', 4, Population);"
